"""download_percentage from integer to float, uuid as string 16

Revision ID: e5cb285f0125
Revises: 
Create Date: 2024-11-18 22:40:32.815553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cb285f0125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.String(length=90000), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('download_percentage', sa.Float(), nullable=True),
    sa.Column('ts_add', sa.Float(), nullable=True),
    sa.Column('ts_finish', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('album_id', sa.String(length=16), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('download_percentage', sa.Float(), nullable=True),
    sa.Column('ts_add', sa.Float(), nullable=True),
    sa.Column('ts_finish', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track')
    op.drop_table('album')
    # ### end Alembic commands ###
